version: '1.0.{build}'
image: Visual Studio 2017
install:
  - dotnet --version
  - dotnet restore
build_script:
  - dotnet build
test_script:
  - ps: ForEach ($proj in (Get-ChildItem -Path test -Recurse -Filter '*.csproj')) { dotnet test $proj.FullName }
